name: Ping Astra DB Every 10 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes UTC
  workflow_dispatch:        # manual trigger option

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install astrapy requests

      - name: Run alive script
        env:
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
        run: python alive.py
